nodeLinker: pnp

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"

  swiper@*:
    dependencies:
      react: "*"

  redux-persist@*:
    dependencies:
      redux: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
