version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app/nginx:/etc/nginx
    environment:
      - NGINX_PORT=80

  web:
    build: Dockerfile
    links:
      - nginx
