import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/common/Header';
import Footer from '../components/common/Footer';
// import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>마켓컬리 :: 내일의 장보기, 마켓컬리</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>Main Area</main>

      <Footer />
    </>
  );
};

export default Home;
