version: '3'

networks:
  dev-net:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: kurlyapp-web-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/html:/usr/share/nginx/html
    networks:
      - dev-net

  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/kurlyapp/web:${GITHUB_WEBAPP_SHA}
    container_name: kurlyapp-web-web
    networks:
      - dev-net
