version: '3'

networks:
  dev-net:
    external: true

services:
  next:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/kurlyapp/web:${GITHUB_WEBAPP_SHA}
    container_name: next
    networks:
      - dev-net
