name: Kurly Web App (PC) Deploy Workflow

env:
  VERSON: 1.0.0

on:
  push:
    branches: [ "test/actions-workflow" ]

jobs:
  build:
    name: Build Docker Image Stage
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          tags: kurlyapp/web:${{ VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deployment:
    name: Deploy Docker Image Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            echo "Connected with Actions!"
