name: Kurly Web App (PC) Deploy Workflow

on:
  push:
    branches: [ "test/actions-workflow" ]

jobs:
  build:
    name: Build Image Stage
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3
      - run: docker build -t kurlyapp/web:$(date +%s) --platform linux/amd64 .
