name: Kurly Web App (PC) Deploy Workflow

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Build Image Stage
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3
        # run: docker build -t kurlyapp/web:$(date +%s) .

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          tags: kurlyapp/web:$(date +%s)
          cache-from: type=gha
          cache-to: type=gha,mode=max


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
