name: Kurly Web App (PC) Deploy Workflow

on:
  push:
    branches: [ "test/actions-workflow" ]

jobs:
#  build:
#    name: Build Docker Image Stage
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Github Checkout
#        uses: actions/checkout@v3
#      - run: docker build -t kurlyapp/web:$(date +%s) --platform linux/amd64 .

  deployment:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
#    needs: build

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secretse.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
