name: Kurly Web App (PC) Deploy Workflow

on:
  push:
    branches: [ "test/actions-workflow" ]

jobs:
  build:
    name: Build Docker Image Stage
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3
      # - run: docker build -t kurlyapp/web:$(date +%s) --platform linux/amd64 .

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          tags: kurlyapp/web:1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: |
          docker save -o kurlyapp-web_1.0.0.tar kurlyapp/web:1.0.0

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "kurlyapp-web_1.0.0.tar"
          target: "app"


  deployment:
    name: Deploy Docker Image Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected with Actions!"
            docker load -i kurlyapp-web_1.0.0.tar
            docker images
